#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export PATH="$HOME/.local/share/nvim/lazy/fzf/bin:$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999

export EDITOR="/usr/local/bin/nvim"
export PATH="/usr/local/go/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"

export PATH="$PATH:/home/luis/.dotnet/tools"
export PATH="$HOME/.local/bin:$PATH"

export LUA_PATH='/usr/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?/init.lua;./?.lua;./?/init.lua;/home/luis/.luarocks/share/lua/5.1/?.lua;/home/luis/.luarocks/share/lua/5.1/?/init.lua'
export LUA_CPATH='/usr/local/lib/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;/usr/lib/lua/5.1/loadall.so;./?.so;/home/luis/.luarocks/lib/lua/5.1/?.so'
export PATH="$PATH:/home/luis/.luarocks/bin"
